services:
  volet:
    build:
      context: https://github.com/Balou866/Domo-store.git#main:app
    container_name: volet-roulant
    ports:
      - "9090:9090"
    environment:
      - ESP32_URL=http://192.168.1.XXX   # ← Remplacer par l'IP de l'ESP32
      - TZ=Europe/Paris
    volumes:
      - volet_data:/app/data
    restart: unless-stopped

volumes:
  volet_data:
